# -*- coding: utf-8 -*-
"""multiclass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPaVFrtBgwb_pkB6kvWqg0Pac3c3ucqo
"""

import pandas as pd
import numpy as np
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)

# Initialize the lemmatizer and stopwords
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    """Preprocess text by removing special characters, lemmatizing, and removing stopwords"""
    # Check if the text is NaN or not a string
    if isinstance(text, str):
        # Convert to lowercase
        text = text.lower()

        # Remove special characters and digits
        text = re.sub(r'[^a-zA-Z\s]', '', text)

        # Tokenize text
        words = text.split()

        # Remove stopwords and lemmatize
        cleaned_words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

        # Join words back into a string
        return ' '.join(cleaned_words)
    else:
        return ""

class TextClassificationDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        # Tokenize the text
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )

        # Remove the batch dimension
        encoding = {k: v.squeeze(0) for k, v in encoding.items()}

        # Add label
        encoding['label'] = torch.tensor(label)

        return encoding

class TextClassifier(nn.Module):
    def __init__(self, bert_model, hidden_dim, output_dim, n_layers=2, dropout=0.3):
        super(TextClassifier, self).__init__()
        self.bert = bert_model
        self.embedding_dim = bert_model.config.hidden_size

        # Freeze BERT parameters to use it only as feature extractor
        for param in self.bert.parameters():
            param.requires_grad = False

        self.lstm = nn.LSTM(
            input_size=self.embedding_dim,
            hidden_size=hidden_dim,
            num_layers=n_layers,
            bidirectional=True,
            batch_first=True,
            dropout=dropout if n_layers > 1 else 0
        )

        # For 6 classes, we'll add a slightly deeper classifier
        self.fc1 = nn.Linear(hidden_dim * 2, hidden_dim)  # *2 for bidirectional
        self.dropout = nn.Dropout(dropout)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, input_ids, attention_mask):
        # Get BERT embeddings
        with torch.no_grad():
            bert_outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
            # Use the last hidden state
            embedded = bert_outputs.last_hidden_state  # [batch_size, seq_len, embedding_dim]

        # Pass through LSTM
        lstm_output, (hidden, cell) = self.lstm(embedded)

        # Concatenate the final forward and backward hidden states
        hidden = torch.cat([hidden[-2], hidden[-1]], dim=1)

        # Pass through the fully connected layers
        x = self.dropout(hidden)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.dropout(x)
        output = self.fc2(x)

        return output

def plot_training_metrics(train_losses, train_accuracies, val_losses, val_accuracies):
    """Plot the training and validation metrics over epochs"""
    epochs = range(1, len(train_losses) + 1)

    plt.figure(figsize=(12, 5))

    # Plot loss
    plt.subplot(1, 2, 1)
    plt.plot(epochs, train_losses, 'b-', label='Training Loss')
    plt.plot(epochs, val_losses, 'r-', label='Validation Loss')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    # Plot accuracy
    plt.subplot(1, 2, 2)
    plt.plot(epochs, train_accuracies, 'b-', label='Training Accuracy')
    plt.plot(epochs, val_accuracies, 'r-', label='Validation Accuracy')
    plt.title('Training and Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.tight_layout()
    plt.savefig('training_metrics.png')
    plt.show()

def plot_confusion_matrix(y_true, y_pred, class_names):
    """Plot the confusion matrix"""
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(10, 8))  # Larger figure for 6 classes
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.savefig('confusion_matrix.png')
    plt.show()

def plot_class_distribution(labels, class_names, title="Class Distribution"):
    """Plot the distribution of classes"""
    plt.figure(figsize=(10, 6))
    counts = np.bincount(labels)
    plt.bar(range(len(counts)), counts)
    plt.xticks(range(len(counts)), class_names, rotation=45, ha='right')
    plt.title(title)
    plt.xlabel('Class')
    plt.ylabel('Count')
    plt.tight_layout()
    plt.savefig(f"{title.lower().replace(' ', '_')}.png")
    plt.show()

# Main function to load data, preprocess, and train the model
def main():
    # Load data from CSV file with latin1 encoding
    # Assuming the CSV has columns 'Text' and 'Label' as specified
    print("Loading data from CSV file...")
    df = pd.read_csv('/content/multi-class.csv', encoding='latin1')

    # Verify column names
    print(f"DataFrame columns: {df.columns.tolist()}")

    # Ensure the required columns exist
    if 'Text' not in df.columns or 'Label' not in df.columns:
        raise ValueError("CSV file must contain 'Text' and 'Label' columns")

    # Preprocess the text
    print("Preprocessing text data...")
    df['processed_text'] = df['Text'].apply(preprocess_text)

    # Check for empty texts after preprocessing and remove them
    empty_texts = df['processed_text'] == ""
    if empty_texts.any():
        print(f"Removing {empty_texts.sum()} empty texts after preprocessing")
        df = df[~empty_texts]

    # Encode labels
    label_encoder = LabelEncoder()
    df['encoded_label'] = label_encoder.fit_transform(df['Hate Category'])
    class_names = label_encoder.classes_
    print(f"Class labels ({len(class_names)}): {class_names}")

    # Check class distribution
    class_counts = df['Label'].value_counts()
    print("Class distribution:")
    for cls, count in class_counts.items():
        print(f"  {cls}: {count} ({count/len(df)*100:.2f}%)")

    # Plot class distribution
    plot_class_distribution(df['encoded_label'].values, class_names)

    # Split the data into train and test sets
    train_df, test_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['encoded_label'])

    # Further split training data to create a validation set
    train_df, val_df = train_test_split(train_df, test_size=0.1, random_state=42, stratify=train_df['encoded_label'])

    print(f"Training samples: {len(train_df)}")
    print(f"Validation samples: {len(val_df)}")
    print(f"Testing samples: {len(test_df)}")

    # Load TinyBERT tokenizer and model
    print("Loading TinyBERT model...")
    tokenizer = AutoTokenizer.from_pretrained("prajjwal1/bert-tiny")
    bert_model = AutoModel.from_pretrained("prajjwal1/bert-tiny")

    # Create datasets
    train_dataset = TextClassificationDataset(
        texts=train_df['processed_text'].tolist(),
        labels=train_df['encoded_label'].tolist(),
        tokenizer=tokenizer
    )

    val_dataset = TextClassificationDataset(
        texts=val_df['processed_text'].tolist(),
        labels=val_df['encoded_label'].tolist(),
        tokenizer=tokenizer
    )

    test_dataset = TextClassificationDataset(
        texts=test_df['processed_text'].tolist(),
        labels=test_df['encoded_label'].tolist(),
        tokenizer=tokenizer
    )

    # Create data loaders
    batch_size = 16
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)
    test_loader = DataLoader(test_dataset, batch_size=batch_size)

    # Initialize model
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    # For 6 classes, we'll use a slightly larger hidden dimension
    hidden_dim = 192
    model = TextClassifier(
        bert_model=bert_model,
        hidden_dim=hidden_dim,
        output_dim=len(class_names)
    ).to(device)

    # Define loss function and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    # Add learning rate scheduler for better convergence
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=2, verbose=True
    )

    # Lists to store metrics for plotting
    train_losses = []
    train_accuracies = []
    val_losses = []
    val_accuracies = []

    # Training loop
    num_epochs = 15  # Increased number of epochs for more complex classification
    print(f"Starting training for {num_epochs} epochs...")

    best_val_acc = 0.0

    for epoch in range(num_epochs):
        # Training phase
        model.train()
        train_loss = 0
        correct_preds = 0
        total_preds = 0

        for batch in train_loader:
            # Move batch to device
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            # Forward pass
            optimizer.zero_grad()
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)

            # Calculate loss
            loss = criterion(outputs, labels)
            train_loss += loss.item()

            # Backward pass and optimize
            loss.backward()
            optimizer.step()

            # Calculate accuracy
            _, predicted = torch.max(outputs.data, 1)
            total_preds += labels.size(0)
            correct_preds += (predicted == labels).sum().item()

        avg_train_loss = train_loss / len(train_loader)
        train_accuracy = correct_preds / total_preds
        train_losses.append(avg_train_loss)
        train_accuracies.append(train_accuracy)

        # Validation phase
        model.eval()
        val_loss = 0
        correct_preds = 0
        total_preds = 0

        with torch.no_grad():
            for batch in val_loader:
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                labels = batch['label'].to(device)

                outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                loss = criterion(outputs, labels)
                val_loss += loss.item()

                _, predicted = torch.max(outputs.data, 1)
                total_preds += labels.size(0)
                correct_preds += (predicted == labels).sum().item()

        avg_val_loss = val_loss / len(val_loader)
        val_accuracy = correct_preds / total_preds
        val_losses.append(avg_val_loss)
        val_accuracies.append(val_accuracy)

        # Update learning rate
        scheduler.step(avg_val_loss)

        print(f'Epoch {epoch+1}/{num_epochs}, '
              f'Train Loss: {avg_train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, '
              f'Val Loss: {avg_val_loss:.4f}, Val Accuracy: {val_accuracy:.4f}')

        # Save best model
        if val_accuracy > best_val_acc:
            best_val_acc = val_accuracy
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_loss': avg_val_loss,
                'val_accuracy': val_accuracy,
                'label_encoder': label_encoder,
                'class_names': class_names
            }, 'tinybert_lstm_best_model.pt')
            print(f"New best model saved with validation accuracy: {val_accuracy:.4f}")

    # Plot training metrics
    plot_training_metrics(train_losses, train_accuracies, val_losses, val_accuracies)
    # Load the best model for evaluation
    print("\nLoading best model for evaluation...")
    checkpoint = torch.load('tinybert_lstm_best_model.pt', map_location=torch.device('cpu'))
    model.load_state_dict(checkpoint['model_state_dict'])
    print(f"Best model from epoch {checkpoint['epoch']+1} with validation accuracy: {checkpoint['val_accuracy']:.4f}")

    # Evaluation on test set
    print("\nEvaluating on test set...")
    model.eval()
    test_loss = 0
    all_preds = []
    all_labels = []
    all_probs = []

    with torch.no_grad():
        for batch in test_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = criterion(outputs, labels)
            test_loss += loss.item()

            # Get probabilities
            probs = torch.nn.functional.softmax(outputs, dim=1)

            _, predicted = torch.max(outputs.data, 1)

            # Store predictions and true labels for metrics
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    avg_test_loss = test_loss / len(test_loader)
    test_accuracy = (np.array(all_preds) == np.array(all_labels)).mean()

    print(f'Test Loss: {avg_test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}')

    # Print classification report
    print("\nClassification Report:")
    report = classification_report(all_labels, all_preds, target_names=class_names, digits=4)
    print(report)

    # Plot confusion matrix
    print("\nGenerating confusion matrix...")
    plot_confusion_matrix(all_labels, all_preds, class_names)

    # Calculate per-class metrics
    print("\nPer-class Performance:")
    for i, class_name in enumerate(class_names):
        class_indices = np.array(all_labels) == i
        class_preds = np.array(all_preds)[class_indices]
        class_true = np.array(all_labels)[class_indices]
        class_accuracy = (class_preds == class_true).mean()
        print(f"Class '{class_name}': Accuracy = {class_accuracy:.4f}, Count = {np.sum(class_indices)}")

    # Save the final model
    torch.save({
        'model_state_dict': model.state_dict(),
        'label_encoder': label_encoder,
        'class_names': class_names
    }, 'tinybert_lstm_6class_final.pt')
    print("Final model saved to 'tinybert_lstm_6class_final.pt'")

    # Function to predict on new text
    def predict(text):
        # Preprocess
        processed_text = preprocess_text(text)

        # Tokenize
        encoding = tokenizer(
            processed_text,
            truncation=True,
            padding='max_length',
            max_length=128,
            return_tensors='pt'
        )

        # Move to device
        input_ids = encoding['input_ids'].to(device)
        attention_mask = encoding['attention_mask'].to(device)

        # Get prediction
        model.eval()
        with torch.no_grad():
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            probs = torch.nn.functional.softmax(outputs, dim=1)
            conf, predicted = torch.max(probs, 1)

        # Decode prediction
        predicted_label = label_encoder.inverse_transform([predicted.item()])[0]
        confidence = conf.item()

        # Get top 3 predictions
        top_probs, top_indices = torch.topk(probs, k=min(3, len(class_names)))
        top_labels = [label_encoder.inverse_transform([idx.item()])[0] for idx in top_indices[0]]
        top_confidences = top_probs[0].tolist()

        return {
            'predicted_label': predicted_label,
            'confidence': confidence,
            'top_3_predictions': [
                {'label': label, 'confidence': conf}
                for label, conf in zip(top_labels, top_confidences)
            ]
        }

    # Example usage
    sample_text = "This is a sample text for classification."
    prediction = predict(sample_text)
    print(f"\nPrediction for '{sample_text}':")
    print(f"Predicted class: {prediction['predicted_label']} with confidence {prediction['confidence']:.4f}")
    print("Top 3 predictions:")
    for pred in prediction['top_3_predictions']:
        print(f"  {pred['label']}: {pred['confidence']:.4f}")

if __name__ == "__main__":
    main()