# -*- coding: utf-8 -*-
"""pareto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Y01kRHNqI6EyARr785MeBguTb_mNsEJ
"""

"""
Pareto efficiency scatter — 2x2, 300 DPI, journal-ready.
Strategy: only Pareto-optimal points are annotated inline (always isolated,
never overlap). Dominated points are color-coded and identified via a
compact in-panel legend. Clean and unambiguous.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D
import numpy as np

# -----------------------------------------------------------
# DATA
# -----------------------------------------------------------
data = {
    "Binary, Code-mixed": {
        "BERT":        (10.0, 0.7410),
        "mBERT":       (10.0, 0.7361),
        "ALBERT":      ( 8.0, 0.7205),
        "HateBERT":    (11.0, 0.7307),
        "XLM-RoBERTa": (10.5, 0.7449),
        "TinyBERT":    ( 1.5, 0.7176),
        "MobileBERT":  ( 3.5, 0.7548),
        "DistilBERT":  ( 4.3, 0.7362),
    },
    "Binary, Translated": {
        "BERT":        (10.0, 0.7466),
        "mBERT":       (10.9, 0.7126),
        "ALBERT":      ( 8.1, 0.7055),
        "HateBERT":    (11.0, 0.7238),
        "XLM-RoBERTa": (10.8, 0.7369),
        "TinyBERT":    ( 1.9, 0.7223),
        "MobileBERT":  ( 4.9, 0.7299),
        "DistilBERT":  ( 8.0, 0.7377),
    },
    "Multi-class, Code-mixed": {
        "BERT":        (10.85, 0.3349),
        "mBERT":       (10.80, 0.3008),
        "ALBERT":      ( 8.90, 0.2016),
        "HateBERT":    (11.00, 0.2386),
        "XLM-RoBERTa": (10.95, 0.2122),
        "TinyBERT":    ( 2.00, 0.2000),
        "MobileBERT":  ( 4.80, 0.2600),
        "DistilBERT":  ( 8.00, 0.3696),
    },
    "Multi-class, Translated": {
        "BERT":        (10.90, 0.5225),
        "mBERT":       (11.00, 0.5440),
        "ALBERT":      ( 8.95, 0.4253),
        "HateBERT":    (11.20, 0.4198),
        "XLM-RoBERTa": (11.30, 0.4654),
        "TinyBERT":    ( 2.10, 0.4984),
        "MobileBERT":  ( 4.90, 0.4680),
        "DistilBERT":  ( 8.10, 0.5465),
    },
}

# -----------------------------------------------------------
# STYLING — distinct, high-contrast, colorblind-friendly
# -----------------------------------------------------------
COLORS = {
    "BERT":        "#1f4e79",
    "mBERT":       "#d35400",
    "ALBERT":      "#27ae60",
    "HateBERT":    "#7e57c2",
    "XLM-RoBERTa": "#e67e22",
    "TinyBERT":    "#0097a7",
    "MobileBERT":  "#c0392b",
    "DistilBERT":  "#5d4037",
}
SLMS = {"TinyBERT", "MobileBERT", "DistilBERT"}
MODEL_ORDER = ["BERT", "mBERT", "ALBERT", "HateBERT", "XLM-RoBERTa",
               "TinyBERT", "MobileBERT", "DistilBERT"]


def pareto_frontier(points):
    sorted_pts = sorted(points, key=lambda p: p[0])
    frontier, best = [], -np.inf
    for pt in sorted_pts:
        if pt[1] > best:
            frontier.append(pt)
            best = pt[1]
    return frontier


# Pareto label offset: SLMs are isolated on the left, encoders sit
# at high t. Use vertical "above" placement throughout for consistency.
def front_label_offset(name, t, f1, points_in_panel):
    """Return (dx_pts, dy_pts, ha) for an inline Pareto-point label."""
    # If a label would land near another point's coordinates, push it up.
    # Simple rule: place label ABOVE the marker, slightly to the right.
    return (0, 14, "center")


# -----------------------------------------------------------
# FIGURE
# -----------------------------------------------------------
plt.rcParams.update({
    "font.family":     "DejaVu Serif",
    "font.size":       10,
    "axes.titlesize":  12.5,
    "axes.labelsize":  10.5,
    "xtick.labelsize":  9.5,
    "ytick.labelsize":  9.5,
    "axes.spines.top":   False,
    "axes.spines.right": False,
})

fig, axes = plt.subplots(2, 2, figsize=(13, 10), dpi=300)
axes = axes.flatten()

config_order = [
    "Binary, Code-mixed",
    "Binary, Translated",
    "Multi-class, Code-mixed",
    "Multi-class, Translated",
]
panel_labels = ["(a)", "(b)", "(c)", "(d)"]

for idx, config in enumerate(config_order):
    ax = axes[idx]
    points = [(t, f1, name) for name, (t, f1) in data[config].items()]
    front = pareto_frontier(points)
    front_names = {p[2] for p in front}
    fx = [p[0] for p in front]
    fy = [p[1] for p in front]

    # Shaded dominated region (light grey wedge)
    ymin_panel = min(p[1] for p in points) - 0.04
    xmax_panel = max(p[0] for p in points) * 1.3
    fx_fill = list(fx) + [xmax_panel, fx[0]]
    fy_fill = list(fy) + [ymin_panel, ymin_panel]
    ax.fill(fx_fill, fy_fill, color="#f1f1f1", alpha=0.6, zorder=1)

    # Pareto frontier dashed line
    ax.plot(fx, fy, linestyle="--", color="black", linewidth=1.4,
            alpha=0.65, zorder=2)

    # Plot points
    for t, f1, name in points:
        is_slm   = name in SLMS
        is_front = name in front_names
        marker   = "o" if is_slm else "s"
        size     = 175 if is_front else 110
        edge_w   = 2.0 if is_front else 0.9
        edge_c   = "#b8860b" if is_front else "black"

        ax.scatter(t, f1, c=COLORS[name], marker=marker, s=size,
                   edgecolor=edge_c, linewidth=edge_w, zorder=4)

        # Inline annotation only for Pareto-optimal points
        if is_front:
            dx, dy, ha = front_label_offset(name, t, f1, points)
            ax.annotate(name, (t, f1),
                        xytext=(dx, dy), textcoords="offset points",
                        fontsize=9.5, fontweight="bold", ha=ha,
                        color="#111111", zorder=6,
                        bbox=dict(boxstyle="round,pad=0.22",
                                  facecolor="white", edgecolor="none",
                                  alpha=0.85))

    # In-panel legend listing every model
    handles = []
    for name in MODEL_ORDER:
        is_slm   = name in SLMS
        is_front = name in front_names
        marker   = "o" if is_slm else "s"
        edge_c   = "#b8860b" if is_front else "black"
        edge_w   = 1.5 if is_front else 0.7
        h = Line2D([0], [0], marker=marker, color="w",
                   markerfacecolor=COLORS[name], markeredgecolor=edge_c,
                   markeredgewidth=edge_w, markersize=9,
                   label=name + (" *" if is_front else ""))
        handles.append(h)
    leg = ax.legend(handles=handles, loc="lower right", fontsize=8.5,
                    frameon=True, ncol=2, columnspacing=0.8,
                    handletextpad=0.4, labelspacing=0.35,
                    framealpha=0.92, edgecolor="#bbbbbb",
                    title="Models  (* = Pareto-optimal)",
                    title_fontsize=8.5)
    leg.get_frame().set_linewidth(0.6)

    # Axes
    ax.set_xscale("log")
    ax.set_xlabel("Execution Time (minutes, log scale)")
    ax.set_ylabel("Macro-F1 Score")
    ax.set_title(f"{panel_labels[idx]}  {config}", loc="left",
                 fontweight="bold", pad=8)

    # Y limits — extra headroom at top for inline labels above markers
    ys = [p[1] for p in points]
    yrange = max(ys) - min(ys)
    ax.set_ylim(min(ys) - max(0.05, yrange * 0.30),
                max(ys) + max(0.05, yrange * 0.30))

    # X limits
    xs = [p[0] for p in points]
    ax.set_xlim(min(xs) * 0.55, max(xs) * 1.55)

    ax.grid(True, which="major", linestyle=":", alpha=0.3, zorder=0)

# -----------------------------------------------------------
# OVERALL CAPTION (bottom)
# -----------------------------------------------------------
shape_legend = [
    Line2D([0], [0], marker="s", color="w", markerfacecolor="gray",
           markeredgecolor="black", markersize=10, label="Large encoder"),
    Line2D([0], [0], marker="o", color="w", markerfacecolor="gray",
           markeredgecolor="black", markersize=10,
           label="Small language model (SLM)"),
    Line2D([0], [0], marker="o", color="w", markerfacecolor="gray",
           markeredgecolor="#b8860b", markeredgewidth=1.8, markersize=12,
           label="Pareto-optimal"),
    Line2D([0], [0], linestyle="--", color="black", alpha=0.65,
           label="Pareto frontier"),
    mpatches.Patch(facecolor="#f1f1f1", alpha=0.7, edgecolor="#cccccc",
                   label="Dominated region"),
]
fig.legend(handles=shape_legend, loc="lower center", ncol=5,
           bbox_to_anchor=(0.5, -0.005), fontsize=10.5,
           frameon=False, handletextpad=0.6, columnspacing=2.0)

# # Overall title + subtitle
# fig.suptitle("Pareto Efficiency: Macro-F1 versus Execution Time across Four Experimental Configurations",
#              fontsize=14, fontweight="bold", y=0.998)
# fig.text(0.5, 0.952,
#          "A model is Pareto-optimal if no other model achieves both lower training time "
#          "and higher Macro-F1. Lightweight SLMs dominate the frontier in all four settings.",
#          ha="center", fontsize=10, style="italic", color="#444444")

plt.tight_layout(rect=[0, 0.04, 1, 0.94])

out = "pareto_efficiency.png" # Changed path to current directory
plt.savefig(out, dpi=300, bbox_inches="tight",
            facecolor="white", edgecolor="none")
print(f"Saved: {out}")

print("\nPareto-optimal models per configuration:")
for config in config_order:
    pts = [(t, f1, name) for name, (t, f1) in data[config].items()]
    front = pareto_frontier(pts)
    print(f"  {config}:")
    for t, f, n in front:
        print(f"     {n:<13} t={t:>5.1f} min,  Macro-F1={f:.4f}")

"""
Translation-gain bar chart — Δ Macro-F1 (translated − code-mixed) per model.
1×2 layout, shared X-axis to expose binary vs multi-class asymmetry.
300 DPI, journal-ready.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# -----------------------------------------------------------
# DATA
# -----------------------------------------------------------
binary_codemixed = {
    "BERT": 0.7410, "mBERT": 0.7361, "ALBERT": 0.7205, "HateBERT": 0.7307,
    "XLM-RoBERTa": 0.7449, "TinyBERT": 0.7176, "MobileBERT": 0.7548, "DistilBERT": 0.7362,
}
binary_translated = {
    "BERT": 0.7466, "mBERT": 0.7126, "ALBERT": 0.7055, "HateBERT": 0.7238,
    "XLM-RoBERTa": 0.7369, "TinyBERT": 0.7223, "MobileBERT": 0.7299, "DistilBERT": 0.7377,
}
multi_codemixed = {
    "BERT": 0.3349, "mBERT": 0.3008, "ALBERT": 0.2016, "HateBERT": 0.2386,
    "XLM-RoBERTa": 0.2122, "TinyBERT": 0.2000, "MobileBERT": 0.2600, "DistilBERT": 0.3696,
}
multi_translated = {
    "BERT": 0.5225, "mBERT": 0.5440, "ALBERT": 0.4253, "HateBERT": 0.4198,
    "XLM-RoBERTa": 0.4654, "TinyBERT": 0.4984, "MobileBERT": 0.4680, "DistilBERT": 0.5465,
}

LARGE  = ["BERT", "mBERT", "ALBERT", "HateBERT", "XLM-RoBERTa"]
SMALL  = ["TinyBERT", "MobileBERT", "DistilBERT"]
MODELS = LARGE + SMALL
SLMS   = set(SMALL)

delta_binary = [binary_translated[m] - binary_codemixed[m] for m in MODELS]
delta_multi  = [multi_translated[m]  - multi_codemixed[m]  for m in MODELS]

# -----------------------------------------------------------
# STYLING
# -----------------------------------------------------------
plt.rcParams.update({
    "font.family":     "DejaVu Serif",
    "font.size":       10,
    "axes.titlesize":  12.5,
    "axes.labelsize":  11,
    "xtick.labelsize": 9.5,
    "ytick.labelsize": 10.5,
    "axes.spines.top":   False,
    "axes.spines.right": False,
})

GAIN_COLOR    = "#2e7d32"
LOSS_COLOR    = "#c62828"
NEUTRAL_COLOR = "#9e9e9e"
SLM_HATCH     = "////"

def bar_color(d, threshold=0.005):
    if d > threshold:    return GAIN_COLOR
    if d < -threshold:   return LOSS_COLOR
    return NEUTRAL_COLOR

# -----------------------------------------------------------
# FIGURE
# -----------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(13.5, 6.2), dpi=300,
                         gridspec_kw={"wspace": 0.25})

GLOBAL_XMIN = -0.05
GLOBAL_XMAX = 0.36

panels = [
    ("(a)  Binary Classification",      delta_binary, np.mean(delta_binary)),
    ("(b)  Multi-class Classification", delta_multi,  np.mean(delta_multi)),
]

y_pos = np.arange(len(MODELS))[::-1]      # invert: BERT at top, DistilBERT at bottom

for ax, (title, deltas, mean_d) in zip(axes, panels):
    for i, (m, d) in enumerate(zip(MODELS, deltas)):
        is_slm = m in SLMS
        color  = bar_color(d)
        ax.barh(y_pos[i], d,
                height=0.66, color=color,
                edgecolor="black", linewidth=0.7,
                hatch=SLM_HATCH if is_slm else None,
                alpha=0.92, zorder=3)

        # Value label — placed smartly based on bar sign
        offset = 0.008
        if d >= 0:
            # Positive bar: label outside to the right
            ax.text(d + offset, y_pos[i], f"+{d:.4f}",
                    va="center", ha="left",
                    fontsize=9.5, fontweight="bold",
                    color="#111111", zorder=4)
        else:
            # Negative bar: place value to the RIGHT of zero, in the
            # whitespace where positive bars would otherwise be.
            # This avoids any collision with y-axis model names.
            ax.text(0.005, y_pos[i], f"{d:.4f}",
                    va="center", ha="left",
                    fontsize=9.5, fontweight="bold",
                    color=LOSS_COLOR, zorder=4)

    # zero reference line
    ax.axvline(0, color="black", linewidth=1.0, zorder=2)

    # subtle horizontal divider between large encoders and SLMs
    sep_y = y_pos[len(LARGE)] + 0.5
    ax.axhline(sep_y, color="#bbbbbb", linewidth=0.7,
               linestyle=":", zorder=1)

    # mean line + annotation, drawn within the data area
    ax.axvline(mean_d, color="#1a4d1a" if mean_d > 0 else "#7a1a1a",
               linewidth=1.1, linestyle="--", alpha=0.7, zorder=2)
    # mean text in upper-right of axis area
    sign = "+" if mean_d >= 0 else ""
    mean_text = f"Mean Δ = {sign}{mean_d:.4f}"
    bbox_face = "#e8f5e9" if mean_d > 0 else "#fdecea"
    bbox_edge = "#4caf50" if mean_d > 0 else "#c62828"
    ax.text(0.97, 0.04, mean_text,
            transform=ax.transAxes,
            ha="right", va="bottom",
            fontsize=10, fontweight="bold",
            color="#1a4d1a" if mean_d > 0 else "#7a1a1a",
            bbox=dict(boxstyle="round,pad=0.4",
                      facecolor=bbox_face, edgecolor=bbox_edge,
                      linewidth=0.8))

    ax.set_yticks(y_pos)
    ax.set_yticklabels(MODELS)
    ax.set_xlim(GLOBAL_XMIN, GLOBAL_XMAX)
    ax.set_xlabel("Δ Macro-F1   (translated − code-mixed)")
    ax.set_title(title, loc="left", fontweight="bold", pad=8)

    ax.grid(True, axis="x", linestyle=":", alpha=0.3, zorder=0)
    ax.set_axisbelow(True)

    # Family bracket labels — on the far right of each panel, vertical
    x_bracket = GLOBAL_XMAX - 0.001
    # Large encoders bracket (top section)
    y_top    = y_pos[0]              + 0.35
    y_bot_le = y_pos[len(LARGE) - 1] - 0.35
    ax.annotate("",
                xy=(x_bracket, y_top), xytext=(x_bracket, y_bot_le),
                arrowprops=dict(arrowstyle="-", color="#888888", lw=1.0),
                zorder=1)
    ax.text(GLOBAL_XMAX + 0.002, (y_top + y_bot_le) / 2,
            "Large\nEncoders", rotation=270, va="center", ha="left",
            fontsize=8.5, color="#666666", style="italic")

    # SLMs bracket (bottom section)
    y_top_slm = y_pos[len(LARGE)] + 0.35
    y_bot     = y_pos[-1]         - 0.35
    ax.annotate("",
                xy=(x_bracket, y_top_slm), xytext=(x_bracket, y_bot),
                arrowprops=dict(arrowstyle="-", color="#888888", lw=1.0),
                zorder=1)
    ax.text(GLOBAL_XMAX + 0.002, (y_top_slm + y_bot) / 2,
            "SLMs", rotation=270, va="center", ha="left",
            fontsize=8.5, color="#666666", style="italic")

# -----------------------------------------------------------
# LEGEND
# -----------------------------------------------------------
legend_handles = [
    mpatches.Patch(facecolor=GAIN_COLOR, edgecolor="black",
                   linewidth=0.7, label="Gain from translation"),
    mpatches.Patch(facecolor=LOSS_COLOR, edgecolor="black",
                   linewidth=0.7, label="Loss from translation"),
    mpatches.Patch(facecolor=NEUTRAL_COLOR, edgecolor="black",
                   linewidth=0.7, label="Negligible change (|Δ| < 0.005)"),
    mpatches.Patch(facecolor="white", edgecolor="black",
                   linewidth=0.7, hatch=SLM_HATCH,
                   label="Small Language Model (SLM)"),
]
fig.legend(handles=legend_handles, loc="lower center", ncol=4,
           bbox_to_anchor=(0.5, -0.04), fontsize=10.5, frameon=False,
           handletextpad=0.6, columnspacing=2.2)

# -----------------------------------------------------------
# TITLE + SUBTITLE
# -----------------------------------------------------------
# fig.suptitle(
#     "Effect of Translation Preprocessing on Macro-F1: Binary vs Multi-class",
#     fontsize=14, fontweight="bold", y=1.00)

# fig.text(0.5, 0.94,
#          "Translation produces marginal — sometimes negative — effects on binary classification, "
#          "but yields large and uniform gains on the multi-class task.",
#          ha="center", fontsize=10.5, style="italic", color="#444444")

plt.subplots_adjust(left=0.08, right=0.95, top=0.86, bottom=0.12)

out = "/content/translation_gain.png"
plt.savefig(out, dpi=300, bbox_inches="tight",
            facecolor="white", edgecolor="none")
print(f"Saved: {out}")

print("\n--- Δ Macro-F1 summary ---")
print(f"{'Model':<13} {'Binary Δ':>10}  {'Multi-class Δ':>14}")
print("-" * 42)
for m, db, dm in zip(MODELS, delta_binary, delta_multi):
    print(f"{m:<13} {db:>+10.4f}  {dm:>+14.4f}")
print("-" * 42)
print(f"{'MEAN':<13} {np.mean(delta_binary):>+10.4f}  {np.mean(delta_multi):>+14.4f}")