# -*- coding: utf-8 -*-
"""Sanjantranslation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4ykT7efd_0RxRp_LIC3KiYeU7Dxrcsb
"""

!pip install transformers

import pandas as pd
from transformers import pipeline

# Initialize the transliteration pipeline with GPU support and set max length to 400
pipe = pipeline("translation", model="ai4bharat/indictrans2-indic-en-1B", device=0, trust_remote_code=True)

def try_read_csv(file_path):
    """
    Try reading CSV file with different encodings
    Args:
        file_path (str): Path to the CSV file
    Returns:
        pandas.DataFrame: Loaded DataFrame
    """
    encodings = [
        'utf-8',
        'latin1',
        'iso-8859-1',
        'cp1252',
        'ascii',
        'utf-16',
        'windows-1252'
    ]

    for encoding in encodings:
        try:
            print(f"Trying encoding: {encoding}")
            df = pd.read_csv(file_path, encoding=encoding)
            print(f"Successfully read file with encoding: {encoding}")
            return df
        except UnicodeDecodeError:
            continue
        except Exception as e:
            print(f"Error with encoding {encoding}: {str(e)}")
            continue

    raise ValueError("Could not read the CSV file with any of the attempted encodings")

def convert_kanglish(text):
    """
    Convert Kanglish text to English using ai4bharat's translation model.
    Args:
        text (str): Input text containing Kanglish content
    Returns:
        str: Converted English text
    """
    try:
        # Handle NaN or non-string values
        if pd.isna(text) or not isinstance(text, str):
            return text

        # Transliterate using the pipeline with max length of 400
        translated_text = pipe(text, max_length=400)[0]['translation_text']
        return translated_text

    except Exception as e:
        print(f"Conversion error for text '{text}': {str(e)}")
        return text

def process_csv_file(input_file, output_file, text_column):
    """
    Read CSV file, convert text, and save results with new column.
    Args:
        input_file (str): Path to input CSV file
        output_file (str): Path to output CSV file
        text_column (str): Name of the column containing text to convert
    """
    try:
        # Try reading the CSV file with different encodings
        df = try_read_csv(input_file)

        # Check if the specified column exists
        if text_column not in df.columns:
            print(f"Available columns: {', '.join(df.columns)}")
            raise ValueError(f"Column '{text_column}' not found in the CSV file")

        # Create new column name for conversions
        converted_column = f"{text_column}_english"

        # Convert each row and store in new column
        print("\nStarting conversion process...")
        total_rows = len(df)

        # Process with progress tracking
        for index, row in df.iterrows():
            if index % 10 == 0:  # Show progress every 10 rows
                print(f"Processing row {index + 1} of {total_rows}")
            df.at[index, converted_column] = convert_kanglish(row[text_column])

        # Save the output file in UTF-8
        df.to_csv(output_file, index=False, encoding='utf-8')
        print(f"Conversion completed. Results saved to {output_file}")

    except Exception as e:
        print(f"Error processing CSV file: {str(e)}")

# Example usage
if __name__ == "__main__":
    # Configuration
    input_csv = "/content/SANJANA_LLM.csv"
    output_csv = "converted_output.csv"
    text_column_name = "Comment"  # Change this to match your column name

    # Process the file
    process_csv_file(input_csv, output_csv, text_column_name)