# -*- coding: utf-8 -*-
"""tinybert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDpE_rzAKPf0JVF9zDN7ClfTUfqYpqc0
"""

import pandas as pd
import numpy as np
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)

# Initialize the lemmatizer and stopwords
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    """Preprocess text by removing special characters, lemmatizing, and removing stopwords"""
    # Convert to lowercase
    text = text.lower()

    # Remove special characters and digits
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Tokenize text
    words = text.split()

    # Remove stopwords and lemmatize
    cleaned_words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

    # Join words back into a string
    return ' '.join(cleaned_words)

class TextClassificationDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        # Tokenize the text
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )

        # Remove the batch dimension
        encoding = {k: v.squeeze(0) for k, v in encoding.items()}

        # Add label
        encoding['label'] = torch.tensor(label)

        return encoding

class TextClassifier(nn.Module):
    def __init__(self, bert_model, hidden_dim, output_dim, n_layers=2, dropout=0.2):
        super(TextClassifier, self).__init__()
        self.bert = bert_model
        self.embedding_dim = bert_model.config.hidden_size

        # Freeze BERT parameters to use it only as feature extractor
        for param in self.bert.parameters():
            param.requires_grad = False

        self.lstm = nn.LSTM(
            input_size=self.embedding_dim,
            hidden_size=hidden_dim,
            num_layers=n_layers,
            bidirectional=True,
            batch_first=True,
            dropout=dropout if n_layers > 1 else 0
        )

        self.fc = nn.Linear(hidden_dim * 2, output_dim)  # *2 for bidirectional
        self.dropout = nn.Dropout(dropout)

    def forward(self, input_ids, attention_mask):
        # Get BERT embeddings
        with torch.no_grad():
            bert_outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
            # Use the last hidden state
            embedded = bert_outputs.last_hidden_state  # [batch_size, seq_len, embedding_dim]

        # Pass through LSTM
        lstm_output, (hidden, cell) = self.lstm(embedded)

        # Concatenate the final forward and backward hidden states
        hidden = self.dropout(torch.cat([hidden[-2], hidden[-1]], dim=1))

        # Pass through the fully connected layer
        output = self.fc(hidden)

        return output

# Main function to load data, preprocess, and train the model
def main():
    # Load data from CSV file
    # Assuming the CSV has columns 'text' and 'label'
    df = pd.read_csv('/content/Dataset.csv',encoding='latin-1')

    # Preprocess the text
    df['processed_text'] = df['Text'].apply(preprocess_text)

    # Encode labels
    label_encoder = LabelEncoder()
    df['encoded_label'] = label_encoder.fit_transform(df['Label'])

    # Split the data
    train_df, test_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['encoded_label'])

    # Load TinyBERT tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained("prajjwal1/bert-tiny")
    bert_model = AutoModel.from_pretrained("prajjwal1/bert-tiny")

    # Create datasets
    train_dataset = TextClassificationDataset(
        texts=train_df['processed_text'].tolist(),
        labels=train_df['encoded_label'].tolist(),
        tokenizer=tokenizer
    )

    test_dataset = TextClassificationDataset(
        texts=test_df['processed_text'].tolist(),
        labels=test_df['encoded_label'].tolist(),
        tokenizer=tokenizer
    )

    # Create data loaders
    train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=16)

    # Initialize model
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = TextClassifier(
        bert_model=bert_model,
        hidden_dim=128,
        output_dim=len(label_encoder.classes_)
    ).to(device)

    # Define loss function and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    # Training loop
    num_epochs = 10
    for epoch in range(num_epochs):
        model.train()
        train_loss = 0
        correct_preds = 0
        total_preds = 0

        for batch in train_loader:
            # Move batch to device
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            # Forward pass
            optimizer.zero_grad()
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)

            # Calculate loss
            loss = criterion(outputs, labels)
            train_loss += loss.item()

            # Backward pass and optimize
            loss.backward()
            optimizer.step()

            # Calculate accuracy
            _, predicted = torch.max(outputs.data, 1)
            total_preds += labels.size(0)
            correct_preds += (predicted == labels).sum().item()

        train_accuracy = correct_preds / total_preds
        train_loss /= len(train_loader)

        print(f'Epoch {epoch+1}/{num_epochs}, Loss: {train_loss:.4f}, Accuracy: {train_accuracy:.4f}')

    # Evaluation
    model.eval()
    test_loss = 0
    correct_preds = 0
    total_preds = 0

    with torch.no_grad():
        for batch in test_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = criterion(outputs, labels)
            test_loss += loss.item()

            _, predicted = torch.max(outputs.data, 1)
            total_preds += labels.size(0)
            correct_preds += (predicted == labels).sum().item()

    test_accuracy = correct_preds / total_preds
    test_loss /= len(test_loader)

    print(f'Test Loss: {test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}')

    # Save the model
    torch.save(model.state_dict(), 'tinybert_lstm_classifier.pt')

    # Function to predict on new text
    def predict(text):
        # Preprocess
        processed_text = preprocess_text(text)

        # Tokenize
        encoding = tokenizer(
            processed_text,
            truncation=True,
            padding='max_length',
            max_length=128,
            return_tensors='pt'
        )

        # Move to device
        input_ids = encoding['input_ids'].to(device)
        attention_mask = encoding['attention_mask'].to(device)

        # Get prediction
        model.eval()
        with torch.no_grad():
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            _, predicted = torch.max(outputs.data, 1)

        # Decode prediction
        predicted_label = label_encoder.inverse_transform([predicted.item()])[0]

        return predicted_label

    # Example usage
    sample_text = "This is a sample text for classification."
    predicted_label = predict(sample_text)
    print(f"Predicted class for '{sample_text}': {predicted_label}")

if __name__ == "__main__":
    main()

# @title Default title text
import pandas as pd
import numpy as np
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)

# Initialize the lemmatizer and stopwords
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    """Preprocess text by removing special characters, lemmatizing, and removing stopwords"""
    # Check if the text is NaN or not a string
    if isinstance(text, str):
        # Convert to lowercase
        text = text.lower()

        # Remove special characters and digits
        text = re.sub(r'[^a-zA-Z\s]', '', text)

        # Tokenize text
        words = text.split()

        # Remove stopwords and lemmatize
        cleaned_words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

        # Join words back into a string
        return ' '.join(cleaned_words)
    else:
        return ""

class TextClassificationDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        # Tokenize the text
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )

        # Remove the batch dimension
        encoding = {k: v.squeeze(0) for k, v in encoding.items()}

        # Add label
        encoding['label'] = torch.tensor(label)

        return encoding

class TextClassifier(nn.Module):
    def __init__(self, bert_model, hidden_dim, output_dim, n_layers=2, dropout=0.2):
        super(TextClassifier, self).__init__()
        self.bert = bert_model
        self.embedding_dim = bert_model.config.hidden_size

        # Freeze BERT parameters to use it only as feature extractor
        for param in self.bert.parameters():
            param.requires_grad = False

        self.lstm = nn.LSTM(
            input_size=self.embedding_dim,
            hidden_size=hidden_dim,
            num_layers=n_layers,
            bidirectional=True,
            batch_first=True,
            dropout=dropout if n_layers > 1 else 0
        )

        self.fc = nn.Linear(hidden_dim * 2, output_dim)  # *2 for bidirectional
        self.dropout = nn.Dropout(dropout)

    def forward(self, input_ids, attention_mask):
        # Get BERT embeddings
        with torch.no_grad():
            bert_outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
            # Use the last hidden state
            embedded = bert_outputs.last_hidden_state  # [batch_size, seq_len, embedding_dim]

        # Pass through LSTM
        lstm_output, (hidden, cell) = self.lstm(embedded)

        # Concatenate the final forward and backward hidden states
        hidden = self.dropout(torch.cat([hidden[-2], hidden[-1]], dim=1))

        # Pass through the fully connected layer
        output = self.fc(hidden)

        return output

def plot_training_metrics(train_losses, train_accuracies, val_losses, val_accuracies):
    """Plot the training and validation metrics over epochs"""
    epochs = range(1, len(train_losses) + 1)

    plt.figure(figsize=(12, 5))

    # Plot loss
    plt.subplot(1, 2, 1)
    plt.plot(epochs, train_losses, 'b-', label='Training Loss')
    plt.plot(epochs, val_losses, 'r-', label='Validation Loss')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    # Plot accuracy
    plt.subplot(1, 2, 2)
    plt.plot(epochs, train_accuracies, 'b-', label='Training Accuracy')
    plt.plot(epochs, val_accuracies, 'r-', label='Validation Accuracy')
    plt.title('Training and Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.tight_layout()
    plt.savefig('training_metrics.png')
    plt.show()

def plot_confusion_matrix(y_true, y_pred, class_names):
    """Plot the confusion matrix"""
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.savefig('confusion_matrix.png')
    plt.show()

# Main function to load data, preprocess, and train the model
def main():
    # Load data from CSV file with latin1 encoding
    # Assuming the CSV has columns 'Text' and 'Label' as specified
    print("Loading data from CSV file...")
    df = pd.read_csv('/content/HASTIKA.csv', encoding='latin1')

    # Verify column names
    print(f"DataFrame columns: {df.columns.tolist()}")

    # Ensure the required columns exist
    if 'Text' not in df.columns or 'Label' not in df.columns:
        raise ValueError("CSV file must contain 'Text' and 'Label' columns")

    # Preprocess the text
    print("Preprocessing text data...")
    df['processed_text'] = df['Text'].apply(preprocess_text)

    # Check for empty texts after preprocessing and remove them
    empty_texts = df['processed_text'] == ""
    if empty_texts.any():
        print(f"Removing {empty_texts.sum()} empty texts after preprocessing")
        df = df[~empty_texts]

    # Encode labels
    label_encoder = LabelEncoder()
    df['encoded_label'] = label_encoder.fit_transform(df['Label'])
    print(f"Class labels: {label_encoder.classes_}")

    # Split the data into train and test sets
    train_df, test_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['encoded_label'])

    # Further split training data to create a validation set
    train_df, val_df = train_test_split(train_df, test_size=0.1, random_state=42, stratify=train_df['encoded_label'])

    print(f"Training samples: {len(train_df)}")
    print(f"Validation samples: {len(val_df)}")
    print(f"Testing samples: {len(test_df)}")

    # Load TinyBERT tokenizer and model
    print("Loading TinyBERT model...")
    tokenizer = AutoTokenizer.from_pretrained("albert/albert-base-v2")
    bert_model = AutoModel.from_pretrained("albert/albert-base-v2")

    # Create datasets
    train_dataset = TextClassificationDataset(
        texts=train_df['processed_text'].tolist(),
        labels=train_df['encoded_label'].tolist(),
        tokenizer=tokenizer
    )

    val_dataset = TextClassificationDataset(
        texts=val_df['processed_text'].tolist(),
        labels=val_df['encoded_label'].tolist(),
        tokenizer=tokenizer
    )

    test_dataset = TextClassificationDataset(
        texts=test_df['processed_text'].tolist(),
        labels=test_df['encoded_label'].tolist(),
        tokenizer=tokenizer
    )

    # Create data loaders
    train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=16)
    test_loader = DataLoader(test_dataset, batch_size=16)

    # Initialize model
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    model = TextClassifier(
        bert_model=bert_model,
        hidden_dim=128,
        output_dim=len(label_encoder.classes_)
    ).to(device)

    # Define loss function and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    # Lists to store metrics for plotting
    train_losses = []
    train_accuracies = []
    val_losses = []
    val_accuracies = []

    # Training loop
    num_epochs = 10
    print(f"Starting training for {num_epochs} epochs...")

    for epoch in range(num_epochs):
        # Training phase
        model.train()
        train_loss = 0
        correct_preds = 0
        total_preds = 0

        for batch in train_loader:
            # Move batch to device
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            # Forward pass
            optimizer.zero_grad()
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)

            # Calculate loss
            loss = criterion(outputs, labels)
            train_loss += loss.item()

            # Backward pass and optimize
            loss.backward()
            optimizer.step()

            # Calculate accuracy
            _, predicted = torch.max(outputs.data, 1)
            total_preds += labels.size(0)
            correct_preds += (predicted == labels).sum().item()

        avg_train_loss = train_loss / len(train_loader)
        train_accuracy = correct_preds / total_preds
        train_losses.append(avg_train_loss)
        train_accuracies.append(train_accuracy)

        # Validation phase
        model.eval()
        val_loss = 0
        correct_preds = 0
        total_preds = 0

        with torch.no_grad():
            for batch in val_loader:
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                labels = batch['label'].to(device)

                outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                loss = criterion(outputs, labels)
                val_loss += loss.item()

                _, predicted = torch.max(outputs.data, 1)
                total_preds += labels.size(0)
                correct_preds += (predicted == labels).sum().item()

        avg_val_loss = val_loss / len(val_loader)
        val_accuracy = correct_preds / total_preds
        val_losses.append(avg_val_loss)
        val_accuracies.append(val_accuracy)

        print(f'Epoch {epoch+1}/{num_epochs}, '
              f'Train Loss: {avg_train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, '
              f'Val Loss: {avg_val_loss:.4f}, Val Accuracy: {val_accuracy:.4f}')

    # Plot training metrics
    plot_training_metrics(train_losses, train_accuracies, val_losses, val_accuracies)

    # Evaluation on test set
    print("\nEvaluating on test set...")
    model.eval()
    test_loss = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for batch in test_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = criterion(outputs, labels)
            test_loss += loss.item()

            _, predicted = torch.max(outputs.data, 1)

            # Store predictions and true labels for metrics
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    avg_test_loss = test_loss / len(test_loader)
    test_accuracy = (np.array(all_preds) == np.array(all_labels)).mean()

    print(f'Test Loss: {avg_test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}')

    # Print classification report
    class_names = label_encoder.classes_
    print("\nClassification Report:")
    report = classification_report(all_labels, all_preds, target_names=class_names, digits=4)
    print(report)

    # Plot confusion matrix
    print("\nGenerating confusion matrix...")
    plot_confusion_matrix(all_labels, all_preds, class_names)

    # Save the model
    torch.save({
        'model_state_dict': model.state_dict(),
        'label_encoder': label_encoder,
        'class_names': class_names
    }, 'tinybert_lstm_classifier.pt')
    print("Model saved to 'tinybert_lstm_classifier.pt'")

    # Function to predict on new text
    def predict(text):
        # Preprocess
        processed_text = preprocess_text(text)

        # Tokenize
        encoding = tokenizer(
            processed_text,
            truncation=True,
            padding='max_length',
            max_length=128,
            return_tensors='pt'
        )

        # Move to device
        input_ids = encoding['input_ids'].to(device)
        attention_mask = encoding['attention_mask'].to(device)

        # Get prediction
        model.eval()
        with torch.no_grad():
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            _, predicted = torch.max(outputs.data, 1)

        # Decode prediction
        predicted_label = label_encoder.inverse_transform([predicted.item()])[0]

        return predicted_label

    # Example usage
    sample_text = "This is a sample text for classification."
    predicted_label = predict(sample_text)
    print(f"\nPredicted class for '{sample_text}': {predicted_label}")

if __name__ == "__main__":
    main()